kind: pipeline
name: build
type: kubernetes

steps:
- name: docker  
  auto_tag: true
  image: infinytum/drone-docker
  settings:
    registry: docker.k8.network
    repo: docker.k8.network/library/scalar
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password


## Import Infinytum Docker Credentials
---
kind: secret
name: docker_username
get:
  path: infinytum-docker
  name: username
---
kind: secret
name: docker_password
get:
  path: infinytum-docker
  name: password