image: registry.infinytum.co/container-images/builder

stages:
  - release

before_script:
  - custom-login

base:
  stage: release
  only:
    - devel
    - tags
  script:
    - if [ "${CI_BUILD_REF_NAME}" = "${CI_COMMIT_TAG}" ]; then export TAG=latest; else export TAG=devel; fi
    - kbuild infinytum/scalar:$TAG