image: registry.infinytum.co/container-images/builder

stages:
  - release

before_script:
  - custom-login

base:
  stage: release
  script:
    - cat /kaniko/.docker/config.json
    - kbuild infinytum/scalar