name: CI for devel and main

on:
  workflow_dispatch:
  push:
    branches:
      - devel
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push dev
        if: github.ref == 'refs/heads/devel'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "infinytum/scalar:devel"

      - name: Build and push main
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "infinytum/scalar:stable,infinytum/scalar:latest"
