name: CI for devel and main

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - devel
  #     - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        env:
          DOCKER_BUILDKIT: 1
          GH_BRANCH_NAME: ${{ steps.branch_name.outputs.branch }}
          SHA: ${{ github.sha }}
        run: |
          docker build                                \
             --build-arg BUILDKIT_INLINE_CACHE=1      \
             --tag infinytum/scalar:latest            \
             --tag             \
             --tag vendor-service .

      - name: Build and push dev
        if: github.ref == 'refs/heads/devel'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "infinytum/scalar:devel,infinytum/scalar:latest"

      - name: Build and push main
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "infinytum/scalar:stable"
